export type ParityStatus = 'done' | 'partial' | 'todo' | 'na';

export const AG_GRID_REACT_SLUGS: string[] = [
  'accessibility',
  'accessing-data',
  'aggregation',
  'aggregation-columns',
  'aggregation-custom-functions',
  'aggregation-filtering',
  'aggregation-total-rows',
  'ag-grid-design-system',
  'ai-toolkit',
  'aligned-grids',
  'cell-content',
  'cell-data-types',
  'cell-editing',
  'cell-editing-batch',
  'cell-editing-full-row',
  'cell-editing-start-stop',
  'cell-editing-validation',
  'cell-editors',
  'cell-expressions',
  'cell-selection',
  'cell-selection-api-reference',
  'cell-selection-fill-handle',
  'cell-selection-handle',
  'cell-styles',
  'cell-text-selection',
  'change-cell-renderers',
  'change-detection',
  'clipboard',
  'codemods',
  'column-api',
  'column-definitions',
  'column-events',
  'column-groups',
  'column-headers',
  'column-headers-components',
  'column-headers-styling',
  'column-interface',
  'column-menu',
  'column-moving',
  'column-object',
  'column-object-group',
  'column-pinning',
  'column-properties',
  'column-sizing',
  'column-spanning',
  'column-state',
  'column-updating-definitions',
  'community-vs-enterprise',
  'compatibility',
  'component-cell-renderer',
  'component-filter',
  'component-filter-legacy',
  'component-floating-filter',
  'component-floating-filter-legacy',
  'component-loading-cell-renderer',
  'component-menu-item',
  'components',
  'component-tool-panel',
  'configuration',
  'context',
  'context-menu',
  'csv-export',
  'custom-icons',
  'data-update',
  'data-update-high-frequency',
  'data-update-row-data',
  'data-update-single-row-cell',
  'data-update-transactions',
  'deep-dive',
  'dom-virtualisation',
  'drag-and-drop',
  'excel-export',
  'excel-export-api',
  'excel-export-columns',
  'excel-export-customising-content',
  'excel-export-data-protection',
  'excel-export-data-types',
  'excel-export-extra-content',
  'excel-export-formulas',
  'excel-export-freeze',
  'excel-export-hyperlinks',
  'excel-export-images',
  'excel-export-master-detail',
  'excel-export-multiple-sheets',
  'excel-export-notes',
  'excel-export-page-setup',
  'excel-export-rows',
  'excel-export-styles',
  'excel-export-tables',
  'excel-import',
  'filter-advanced',
  'filter-api',
  'filter-applying',
  'filter-bigint',
  'filter-conditions',
  'filter-date',
  'filter-external',
  'filtering',
  'filtering-overview',
  'filter-multi',
  'filter-number',
  'filter-quick',
  'filter-set',
  'filter-set-api',
  'filter-set-data-updates',
  'filter-set-excel-mode',
  'filter-set-filter-list',
  'filter-set-mini-filter',
  'filter-set-tree-list',
  'filter-text',
  'find',
  'floating-filters',
  'formula-custom-functions',
  'formula-editor-component',
  'formula-reference',
  'formulas',
  'full-width-rows',
  'getting-started',
  'grid-api',
  'grid-events',
  'grid-interface',
  'grid-lifecycle',
  'grid-options',
  'grid-size',
  'grid-state',
  'grouping',
  'grouping-custom-group-columns',
  'grouping-data',
  'grouping-display-types',
  'grouping-edit',
  'grouping-group-panel',
  'grouping-group-rows',
  'grouping-multiple-group-columns',
  'grouping-opening-groups',
  'grouping-row-dragging',
  'grouping-row-selection',
  'grouping-single-group-column',
  'grouping-sorting',
  'infinite-scrolling',
  'installation',
  'integrated-charts',
  'integrated-charts-api-cross-filter-chart',
  'integrated-charts-api-downloading-image',
  'integrated-charts-api-pivot-chart',
  'integrated-charts-api-range-chart',
  'integrated-charts-api-save-restore-charts',
  'integrated-charts-application-created',
  'integrated-charts-chart-tool-panels',
  'integrated-charts-chart-types',
  'integrated-charts-container',
  'integrated-charts-customisation',
  'integrated-charts-events',
  'integrated-charts-installation',
  'integrated-charts-menu',
  'integrated-charts-pivot-chart',
  'integrated-charts-range-chart',
  'integrated-charts-time-series',
  'integrated-charts-user-created',
  'keyboard-navigation',
  'key-features',
  'license-install',
  'localisation',
  'massive-row-count',
  'master-detail',
  'master-detail-custom-detail',
  'master-detail-grids',
  'master-detail-height',
  'master-detail-master-rows',
  'master-detail-nesting',
  'master-detail-other',
  'master-detail-refresh',
  'mcp-server',
  'migration',
  'modules',
  'notes',
  'overlays',
  'overlays-active',
  'overlays-overview',
  'overlays-provided',
  'pivoting',
  'pivoting-column-groups',
  'pivoting-result-columns',
  'pivoting-totals',
  'printing',
  'provided-cell-editors',
  'provided-cell-editors-checkbox',
  'provided-cell-editors-date',
  'provided-cell-editors-large-text',
  'provided-cell-editors-number',
  'provided-cell-editors-rich-select',
  'provided-cell-editors-rich-select-async',
  'provided-cell-editors-rich-select-customisation',
  'provided-cell-editors-select',
  'provided-cell-editors-text',
  'react-hooks',
  'reference',
  'reference-data',
  'row-animation',
  'row-dragging',
  'row-dragging-customisation',
  'row-dragging-managed',
  'row-dragging-to-external-dropzone',
  'row-dragging-to-grid',
  'row-dragging-unmanaged',
  'row-events',
  'row-height',
  'row-ids',
  'row-interface',
  'row-models',
  'row-numbers',
  'row-object',
  'row-pagination',
  'row-pinning',
  'row-selection',
  'row-selection-api-reference',
  'row-selection-multi-row',
  'row-selection-single-row',
  'row-sorting',
  'row-spanning',
  'row-styles',
  'rtl',
  'saving-content',
  'scrolling-performance',
  'security',
  'server-side-model',
  'server-side-model-api-reference',
  'server-side-model-changing-columns',
  'server-side-model-configuration',
  'server-side-model-datasource',
  'server-side-model-filtering',
  'server-side-model-grouping',
  'server-side-model-master-detail',
  'server-side-model-pagination',
  'server-side-model-pivoting',
  'server-side-model-retry',
  'server-side-model-row-height',
  'server-side-model-selection',
  'server-side-model-sorting',
  'server-side-model-tree-data',
  'server-side-model-updating',
  'server-side-model-updating-refresh',
  'server-side-model-updating-single-row',
  'server-side-model-updating-transactions',
  'server-side-operations-graphql',
  'server-side-operations-nodejs',
  'server-side-operations-oracle',
  'server-side-operations-spark',
  'side-bar',
  'solidjs',
  'sparklines-api-sparkline-area',
  'sparklines-api-sparkline-bar',
  'sparklines-api-sparkline-line',
  'sparklines-api-sparkline-options',
  'sparklines-area-customisation',
  'sparklines-axis-types',
  'sparklines-bar-customisation',
  'sparklines-column-customisation',
  'sparklines-data',
  'sparklines-installation',
  'sparklines-line-customisation',
  'sparklines-overview',
  'sparklines-points-of-interest',
  'sparklines-tooltips',
  'status-bar',
  'styling-tutorial',
  'supported-browsers',
  'testing',
  'themes',
  'theming',
  'theming-api',
  'theming-borders',
  'theming-colors',
  'theming-compactness',
  'theming-css',
  'theming-distribution',
  'theming-fonts',
  'theming-headers',
  'theming-master-detail',
  'theming-migration',
  'theming-parameters',
  'theming-parts',
  'theming-popups',
  'theming-selections',
  'theming-theme-builder',
  'theming-tool-panels',
  'theming-v32',
  'theming-v32-custom-icons',
  'theming-v32-customisation',
  'theming-v32-customisation-borders',
  'theming-v32-customisation-colours',
  'theming-v32-customisation-compactness',
  'theming-v32-customisation-css',
  'theming-v32-customisation-headers',
  'theming-v32-customisation-popups',
  'theming-v32-customisation-sass',
  'theming-v32-customisation-sass-legacy',
  'theming-v32-customisation-selections',
  'theming-v32-customisation-tool-panels',
  'theming-v32-customisation-variables',
  'theming-v32-customisation-widgets',
  'theming-v32-themes',
  'theming-v32-upgrading-to-v28',
  'theming-v32-upgrading-to-v28-css',
  'theming-v32-upgrading-to-v28-sass',
  'theming-widgets',
  'toolbar',
  'tool-panel',
  'tool-panel-columns',
  'tool-panel-filters',
  'tool-panel-filters-new',
  'tooltips',
  'touch',
  'tree-data',
  'tree-data-data',
  'tree-data-filtering',
  'tree-data-group-column',
  'tree-data-nesting',
  'tree-data-opening-groups',
  'tree-data-paths',
  'tree-data-row-dragging',
  'tree-data-selection',
  'tree-data-self-referential',
  'typescript-generics',
  'undo-redo-edits',
  'upgrading-to-ag-grid-26',
  'upgrading-to-ag-grid-27',
  'upgrading-to-ag-grid-28',
  'upgrading-to-ag-grid-29',
  'upgrading-to-ag-grid-30',
  'upgrading-to-ag-grid-31',
  'upgrading-to-ag-grid-31-1',
  'upgrading-to-ag-grid-31-2',
  'upgrading-to-ag-grid-31-3',
  'upgrading-to-ag-grid-32',
  'upgrading-to-ag-grid-32-1',
  'upgrading-to-ag-grid-32-2-1',
  'upgrading-to-ag-grid-32-3',
  'upgrading-to-ag-grid-33',
  'upgrading-to-ag-grid-33-1',
  'upgrading-to-ag-grid-33-2',
  'upgrading-to-ag-grid-33-3',
  'upgrading-to-ag-grid-34',
  'upgrading-to-ag-grid-34-1',
  'upgrading-to-ag-grid-34-2',
  'upgrading-to-ag-grid-34-3',
  'upgrading-to-ag-grid-35',
  'upgrading-to-ag-grid-35-1',
  'upgrading-to-ag-grid-35-2',
  'upgrading-to-ag-grid-35-3',
  'upgrading-to-older-versions',
  'value-cache',
  'value-formatters',
  'value-getters',
  'value-parsers',
  'value-setters',
  'videos',
  'viewport',
  'view-refresh',
];

export const PARITY_STATUS: Record<string, ParityStatus> = {
  'accessibility': 'done',
  'accessing-data': 'done',
  'aggregation': 'done',
  'aggregation-columns': 'done',
  'aggregation-custom-functions': 'done',
  'aggregation-filtering': 'done',
  'aggregation-total-rows': 'done',
  'ag-grid-design-system': 'done',
  'ai-toolkit': 'done',
  'aligned-grids': 'done',
  'cell-content': 'done',
  'cell-data-types': 'done',
  'cell-editing': 'done',
  'cell-editing-batch': 'done',
  'cell-editing-full-row': 'done',
  'cell-editing-start-stop': 'done',
  'cell-editing-validation': 'done',
  'cell-editors': 'done',
  'cell-expressions': 'done',
  'cell-selection': 'done',
  'cell-selection-api-reference': 'done',
  'cell-selection-fill-handle': 'done',
  'cell-selection-handle': 'done',
  'cell-styles': 'done',
  'cell-text-selection': 'done',
  'change-cell-renderers': 'done',
  'change-detection': 'done',
  'clipboard': 'done',
  'codemods': 'na',
  'column-api': 'done',
  'column-definitions': 'done',
  'column-events': 'done',
  'column-groups': 'done',
  'column-headers': 'done',
  'column-headers-components': 'done',
  'column-headers-styling': 'done',
  'column-interface': 'done',
  'column-menu': 'done',
  'column-moving': 'done',
  'column-object': 'done',
  'column-object-group': 'done',
  'column-pinning': 'done',
  'column-properties': 'done',
  'column-sizing': 'done',
  'column-spanning': 'done',
  'column-state': 'done',
  'column-updating-definitions': 'done',
  'community-vs-enterprise': 'done',
  'compatibility': 'done',
  'component-cell-renderer': 'done',
  'component-filter': 'done',
  'component-filter-legacy': 'done',
  'component-floating-filter': 'done',
  'component-floating-filter-legacy': 'done',
  'component-loading-cell-renderer': 'done',
  'component-menu-item': 'done',
  'components': 'done',
  'component-tool-panel': 'done',
  'configuration': 'done',
  'context': 'done',
  'context-menu': 'done',
  'csv-export': 'done',
  'custom-icons': 'done',
  'data-update': 'done',
  'data-update-high-frequency': 'done',
  'data-update-row-data': 'done',
  'data-update-single-row-cell': 'done',
  'data-update-transactions': 'done',
  'deep-dive': 'done',
  'dom-virtualisation': 'done',
  'drag-and-drop': 'done',
  'excel-export': 'done',
  'excel-export-api': 'done',
  'excel-export-columns': 'done',
  'excel-export-customising-content': 'done',
  'excel-export-data-protection': 'done',
  'excel-export-data-types': 'done',
  'excel-export-extra-content': 'done',
  'excel-export-formulas': 'done',
  'excel-export-freeze': 'done',
  'excel-export-hyperlinks': 'done',
  'excel-export-images': 'done',
  'excel-export-master-detail': 'done',
  'excel-export-multiple-sheets': 'done',
  'excel-export-notes': 'done',
  'excel-export-page-setup': 'done',
  'excel-export-rows': 'done',
  'excel-export-styles': 'done',
  'excel-export-tables': 'done',
  'excel-import': 'done',
  'filter-advanced': 'done',
  'filter-api': 'done',
  'filter-applying': 'done',
  'filter-bigint': 'done',
  'filter-conditions': 'done',
  'filter-date': 'done',
  'filter-external': 'done',
  'filtering': 'done',
  'filtering-overview': 'done',
  'filter-multi': 'done',
  'filter-number': 'done',
  'filter-quick': 'done',
  'filter-set': 'done',
  'filter-set-api': 'done',
  'filter-set-data-updates': 'done',
  'filter-set-excel-mode': 'done',
  'filter-set-filter-list': 'done',
  'filter-set-mini-filter': 'done',
  'filter-set-tree-list': 'done',
  'filter-text': 'done',
  'find': 'done',
  'floating-filters': 'done',
  'formula-custom-functions': 'done',
  'formula-editor-component': 'done',
  'formula-reference': 'done',
  'formulas': 'done',
  'full-width-rows': 'done',
  'getting-started': 'done',
  'grid-api': 'done',
  'grid-events': 'done',
  'grid-interface': 'done',
  'grid-lifecycle': 'done',
  'grid-options': 'done',
  'grid-size': 'done',
  'grid-state': 'done',
  'grouping': 'done',
  'grouping-custom-group-columns': 'done',
  'grouping-data': 'done',
  'grouping-display-types': 'done',
  'grouping-edit': 'done',
  'grouping-group-panel': 'done',
  'grouping-group-rows': 'done',
  'grouping-multiple-group-columns': 'done',
  'grouping-opening-groups': 'done',
  'grouping-row-dragging': 'done',
  'grouping-row-selection': 'done',
  'grouping-single-group-column': 'done',
  'grouping-sorting': 'done',
  'infinite-scrolling': 'done',
  'installation': 'done',
  'integrated-charts': 'na',
  'integrated-charts-api-cross-filter-chart': 'na',
  'integrated-charts-api-downloading-image': 'na',
  'integrated-charts-api-pivot-chart': 'na',
  'integrated-charts-api-range-chart': 'na',
  'integrated-charts-api-save-restore-charts': 'na',
  'integrated-charts-application-created': 'na',
  'integrated-charts-chart-tool-panels': 'na',
  'integrated-charts-chart-types': 'na',
  'integrated-charts-container': 'na',
  'integrated-charts-customisation': 'na',
  'integrated-charts-events': 'na',
  'integrated-charts-installation': 'na',
  'integrated-charts-menu': 'na',
  'integrated-charts-pivot-chart': 'na',
  'integrated-charts-range-chart': 'na',
  'integrated-charts-time-series': 'na',
  'integrated-charts-user-created': 'na',
  'keyboard-navigation': 'done',
  'key-features': 'done',
  'license-install': 'done',
  'localisation': 'done',
  'massive-row-count': 'done',
  'master-detail': 'done',
  'master-detail-custom-detail': 'done',
  'master-detail-grids': 'done',
  'master-detail-height': 'done',
  'master-detail-master-rows': 'done',
  'master-detail-nesting': 'done',
  'master-detail-other': 'done',
  'master-detail-refresh': 'done',
  'mcp-server': 'done',
  'migration': 'na',
  'modules': 'done',
  'notes': 'done',
  'overlays': 'done',
  'overlays-active': 'done',
  'overlays-overview': 'done',
  'overlays-provided': 'done',
  'pivoting': 'done',
  'pivoting-column-groups': 'done',
  'pivoting-result-columns': 'done',
  'pivoting-totals': 'done',
  'printing': 'done',
  'provided-cell-editors': 'done',
  'provided-cell-editors-checkbox': 'done',
  'provided-cell-editors-date': 'done',
  'provided-cell-editors-large-text': 'done',
  'provided-cell-editors-number': 'done',
  'provided-cell-editors-rich-select': 'done',
  'provided-cell-editors-rich-select-async': 'done',
  'provided-cell-editors-rich-select-customisation': 'done',
  'provided-cell-editors-select': 'done',
  'provided-cell-editors-text': 'done',
  'react-hooks': 'done',
  'reference': 'done',
  'reference-data': 'done',
  'row-animation': 'done',
  'row-dragging': 'done',
  'row-dragging-customisation': 'done',
  'row-dragging-managed': 'done',
  'row-dragging-to-external-dropzone': 'done',
  'row-dragging-to-grid': 'done',
  'row-dragging-unmanaged': 'done',
  'row-events': 'done',
  'row-height': 'done',
  'row-ids': 'done',
  'row-interface': 'done',
  'row-models': 'done',
  'row-numbers': 'done',
  'row-object': 'done',
  'row-pagination': 'done',
  'row-pinning': 'done',
  'row-selection': 'done',
  'row-selection-api-reference': 'done',
  'row-selection-multi-row': 'done',
  'row-selection-single-row': 'done',
  'row-sorting': 'done',
  'row-spanning': 'done',
  'row-styles': 'done',
  'rtl': 'done',
  'saving-content': 'done',
  'scrolling-performance': 'done',
  'security': 'done',
  'server-side-model': 'done',
  'server-side-model-api-reference': 'done',
  'server-side-model-changing-columns': 'done',
  'server-side-model-configuration': 'done',
  'server-side-model-datasource': 'done',
  'server-side-model-filtering': 'done',
  'server-side-model-grouping': 'done',
  'server-side-model-master-detail': 'done',
  'server-side-model-pagination': 'done',
  'server-side-model-pivoting': 'done',
  'server-side-model-retry': 'done',
  'server-side-model-row-height': 'done',
  'server-side-model-selection': 'done',
  'server-side-model-sorting': 'done',
  'server-side-model-tree-data': 'done',
  'server-side-model-updating': 'done',
  'server-side-model-updating-refresh': 'done',
  'server-side-model-updating-single-row': 'done',
  'server-side-model-updating-transactions': 'done',
  'server-side-operations-graphql': 'done',
  'server-side-operations-nodejs': 'done',
  'server-side-operations-oracle': 'done',
  'server-side-operations-spark': 'done',
  'side-bar': 'done',
  'solidjs': 'na',
  'sparklines-api-sparkline-area': 'done',
  'sparklines-api-sparkline-bar': 'done',
  'sparklines-api-sparkline-line': 'done',
  'sparklines-api-sparkline-options': 'done',
  'sparklines-area-customisation': 'done',
  'sparklines-axis-types': 'done',
  'sparklines-bar-customisation': 'done',
  'sparklines-column-customisation': 'done',
  'sparklines-data': 'done',
  'sparklines-installation': 'done',
  'sparklines-line-customisation': 'done',
  'sparklines-overview': 'done',
  'sparklines-points-of-interest': 'done',
  'sparklines-tooltips': 'done',
  'status-bar': 'done',
  'styling-tutorial': 'done',
  'supported-browsers': 'done',
  'testing': 'done',
  'themes': 'done',
  'theming': 'done',
  'theming-api': 'done',
  'theming-borders': 'done',
  'theming-colors': 'done',
  'theming-compactness': 'done',
  'theming-css': 'done',
  'theming-distribution': 'done',
  'theming-fonts': 'done',
  'theming-headers': 'done',
  'theming-master-detail': 'done',
  'theming-migration': 'done',
  'theming-parameters': 'done',
  'theming-parts': 'done',
  'theming-popups': 'done',
  'theming-selections': 'done',
  'theming-theme-builder': 'done',
  'theming-tool-panels': 'done',
  'theming-v32': 'done',
  'theming-v32-custom-icons': 'done',
  'theming-v32-customisation': 'done',
  'theming-v32-customisation-borders': 'done',
  'theming-v32-customisation-colours': 'done',
  'theming-v32-customisation-compactness': 'done',
  'theming-v32-customisation-css': 'done',
  'theming-v32-customisation-headers': 'done',
  'theming-v32-customisation-popups': 'done',
  'theming-v32-customisation-sass': 'done',
  'theming-v32-customisation-sass-legacy': 'na',
  'theming-v32-customisation-selections': 'done',
  'theming-v32-customisation-tool-panels': 'done',
  'theming-v32-customisation-variables': 'done',
  'theming-v32-customisation-widgets': 'done',
  'theming-v32-themes': 'done',
  'theming-v32-upgrading-to-v28': 'na',
  'theming-v32-upgrading-to-v28-css': 'na',
  'theming-v32-upgrading-to-v28-sass': 'na',
  'theming-widgets': 'done',
  'toolbar': 'done',
  'tool-panel': 'done',
  'tool-panel-columns': 'done',
  'tool-panel-filters': 'done',
  'tool-panel-filters-new': 'done',
  'tooltips': 'done',
  'touch': 'done',
  'tree-data': 'done',
  'tree-data-data': 'done',
  'tree-data-filtering': 'done',
  'tree-data-group-column': 'done',
  'tree-data-nesting': 'done',
  'tree-data-opening-groups': 'done',
  'tree-data-paths': 'done',
  'tree-data-row-dragging': 'done',
  'tree-data-selection': 'done',
  'tree-data-self-referential': 'done',
  'typescript-generics': 'done',
  'undo-redo-edits': 'done',
  'upgrading-to-ag-grid-26': 'na',
  'upgrading-to-ag-grid-27': 'na',
  'upgrading-to-ag-grid-28': 'na',
  'upgrading-to-ag-grid-29': 'na',
  'upgrading-to-ag-grid-30': 'na',
  'upgrading-to-ag-grid-31': 'na',
  'upgrading-to-ag-grid-31-1': 'na',
  'upgrading-to-ag-grid-31-2': 'na',
  'upgrading-to-ag-grid-31-3': 'na',
  'upgrading-to-ag-grid-32': 'na',
  'upgrading-to-ag-grid-32-1': 'na',
  'upgrading-to-ag-grid-32-2-1': 'na',
  'upgrading-to-ag-grid-32-3': 'na',
  'upgrading-to-ag-grid-33': 'na',
  'upgrading-to-ag-grid-33-1': 'na',
  'upgrading-to-ag-grid-33-2': 'na',
  'upgrading-to-ag-grid-33-3': 'na',
  'upgrading-to-ag-grid-34': 'na',
  'upgrading-to-ag-grid-34-1': 'na',
  'upgrading-to-ag-grid-34-2': 'na',
  'upgrading-to-ag-grid-34-3': 'na',
  'upgrading-to-ag-grid-35': 'na',
  'upgrading-to-ag-grid-35-1': 'na',
  'upgrading-to-ag-grid-35-2': 'na',
  'upgrading-to-ag-grid-35-3': 'na',
  'upgrading-to-older-versions': 'na',
  'value-cache': 'done',
  'value-formatters': 'done',
  'value-getters': 'done',
  'value-parsers': 'done',
  'value-setters': 'done',
  'videos': 'na',
  'viewport': 'done',
  'view-refresh': 'done',
};
